In [5]:
import pandas as pd
import csv
import random


global peso
peso =0.5

path = r"C:\Users\User\Documents\AI\f1\exemplo1.dat"
df = pd.read_csv(path, delimiter=' ')
display(df)

def calculo(x1,x2,peso1, peso2):
    soma = (float(x1)*peso1) + (float(x2)*peso2)
    return soma

def degrau(x):
    if x <= 0 :
        saida =  0
    else:
        saida = 1
    return saida

#abrir o ficheiro em modo da leitura
#with open('exemplo1.dat', 'r') as file_csv :
with open(path, 'r') as file_csv :
    #crie um objecto leitor csv
    reader_csv = csv.reader(file_csv, delimiter =' ')
    random.seed(53217)
    #ler apenas o primeiri registro
    #first_line = next(reader_csv)
    #ler o priimeiirodado do     primeiro  rregistro
    #first_data = first_line[0]
    #second_data = first_line[1]
    #print(f'first data of first register:{first_data}')
    #print(f'second data of first register:{second_data}')
    #itera sobre linhas do aquivo csv - ensure all I/O operations are part of the with block to avoid valueError I/O

    for linhas in reader_csv:
            #ler apenas o primeiri registro
            #first_line = next(reader_csv)
            #ler o priimeiirodado do     primeiro  rregistro
            first_data = linhas[0]
            second_data = linhas[1]
            second_data_=float(second_data)
            print(f'first data of first register:{first_data}')
            print(f'second data of first register:{second_data}')
            somatorio = calculo(float(first_data), float(second_data), peso, peso)
            saida  = degrau(somatorio)
            print('somatorio : ', somatorio)
            print('saida :  ', saida)

print('*' * 20)       

"""
somatorio = calculo(1,0, 0.5, 0.5)
saida  = degrau(somatorio)
print('somatorio : ', somatorio)
print('saida :  ', saida)
"""

    1.5  40  0
0  1.52  41  0
1  1.56  43  0
2  1.54  45  0
3  1.50  37  0
4  1.62  47  1
5  1.70  52  1
6  1.53  63  1
7  1.63  44  1
8  1.57  50  1

first data of first register:1.5
second data of first register:40
somatorio :  20.75
saida :   1
first data of first register:1.52
second data of first register:41
somatorio :  21.26
saida :   1
first data of first register:1.56
second data of first register:43
somatorio :  22.28
saida :   1
first data of first register:1.54
second data of first register:45
somatorio :  23.27
saida :   1
first data of first register:1.5
second data of first register:37
somatorio :  19.25
saida :   1
first data of first register:1.62
second data of first register:47
somatorio :  24.31
saida :   1
first data of first register:1.70
second data of first register:52
somatorio :  26.85
saida :   1
first data of first register:1.53
second data of first register:63
somatorio :  32.265
saida :   1
first data of first register:1.63
second data of first register:44
somatorio :  22.815
saida :   1
first data of first register:1.57
second data of first register:50
somatorio :  25.785
saida :   1
********************

"\nsomatorio = calculo(1,0, 0.5, 0.5)\nsaida  = degrau(somatorio)\nprint('somatorio : ', somatorio)\nprint('saida :  ', saida)\n"